//! `unisonfs init` — install the `sgrep` transparent grep override.
//!
//! `sgrep` routes semantic searches through the Unison brain API when
//! running inside a mounted brain directory (detected via `.unisonfs`
//! marker), and falls back to regular `grep` otherwise.

use anyhow::Result;
use clap::Args as ClapArgs;
use std::io::Write;

#[derive(ClapArgs, Debug)]
pub struct Args {
    /// Shell to install for (bash or zsh). Auto-detected if omitted.
    #[arg(long)]
    pub shell: Option<String>,

    /// Also write a `.unisonfs` marker file in the current directory.
    #[arg(long)]
    pub marker: bool,

    /// Tag to write into the marker file (only relevant with --marker).
    #[arg(long)]
    pub tag: Option<String>,
}

pub async fn run(args: Args) -> Result<()> {
    let shell = args.shell.unwrap_or_else(detect_shell);

    // The sgrep function detects whether it's inside a unisonfs mount via the
    // .unisonfs marker file, and routes to `unisonfs grep` when inside one.
    let wrapper = r#"
# sgrep — transparent semantic grep over the Unison brain
# Installed by `unisonfs init`. Routes to `unisonfs grep` inside a mount.
sgrep() {
    # Walk up looking for a .unisonfs marker
    local _dir="$PWD"
    while [[ "$_dir" != "/" ]]; do
        if [[ -f "$_dir/.unisonfs" ]]; then
            unisonfs grep "$@"
            return $?
        fi
        _dir="${_dir%/*}"
    done
    # Fallback to regular grep
    command grep "$@"
}
"#;

    let rc_path = match shell.as_str() {
        "bash" => {
            let home = std::env::var("HOME").unwrap_or_default();
            std::path::PathBuf::from(home).join(".bashrc")
        }
        "zsh" => {
            let home = std::env::var("HOME").unwrap_or_default();
            std::path::PathBuf::from(home).join(".zshrc")
        }
        other => {
            anyhow::bail!("unsupported shell '{}'; run manually:\n{}", other, wrapper.trim());
        }
    };

    // Append only if not already there
    let existing = std::fs::read_to_string(&rc_path).unwrap_or_default();
    if existing.contains("sgrep — transparent semantic grep") {
        eprintln!("sgrep wrapper already installed in {}", rc_path.display());
    } else {
        let mut file = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&rc_path)?;
        writeln!(file, "{wrapper}")?;
        eprintln!("Installed sgrep wrapper in {}.", rc_path.display());
        eprintln!("Reload your shell: source {}", rc_path.display());
    }

    // Optionally write a .unisonfs marker file in the current directory.
    if args.marker {
        let cwd = std::env::current_dir()?;
        let marker = super::marker::UnisonMarker {
            tag: args.tag.clone(),
            path: None,
            description: Some("auto-generated by `unisonfs init --marker`".to_string()),
        };
        let text = super::marker::format_marker(&marker);
        let path = cwd.join(super::marker::MARKER_FILENAME);
        std::fs::write(&path, &text)?;
        eprintln!("Wrote {}", path.display());
        if let Some(tag) = &args.tag {
            eprintln!("  tag = {tag}");
        }
    }

    Ok(())
}

fn detect_shell() -> String {
    if let Ok(shell) = std::env::var("SHELL") {
        if shell.contains("zsh") {
            return "zsh".to_string();
        }
        if shell.contains("bash") {
            return "bash".to_string();
        }
    }
    "bash".to_string()
}
